# Generated by Django 5.2 on 2025-04-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('order_address', models.TextField()),
                ('price_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'ORDERS',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('Regular', 'Regular'), ('Thrift', 'Thrift'), ('Auction', 'Auction')], default='Regular', max_length=50)),
                ('product_condition', models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('refurbishment_details', models.TextField(blank=True, null=True)),
                ('thrift_condition_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Seller',
                'db_table': 'SELLER',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('courier_service', models.CharField(max_length=50)),
                ('tracking_id', models.CharField(max_length=25, unique=True)),
                ('delivery_status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.orders')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Delivery',
                'db_table': 'DELIVERY',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.product'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('volume', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'INVENTORY',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.seller'),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('tracking_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.delivery')),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Tracking',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('transaction_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_details', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.orders')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction',
                'db_table': 'TRANSACTION',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.user'),
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('bid_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Won', 'Won'), ('Lost', 'Lost')], default='Pending', max_length=50)),
                ('initial_bid_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('auto_bid_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_auto_bid', models.BooleanField(default=False)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.user')),
            ],
            options={
                'verbose_name': 'Bidding',
                'verbose_name_plural': 'Bidding',
                'db_table': 'BIDDING',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.user')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'db_table': 'PRODUCT_REVIEW',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
