# Generated by Django 5.2 on 2025-04-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidbuygo', '0001_initial'),
    ]

    operations = [
    ]
