# Generated by Django 5.2 on 2025-04-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidbuygo', '0002_size_product_auction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidbuygo.seller'),
        ),
    ]
