# Generated by Django 5.2 on 2025-04-19 08:20

import bidbuygo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidbuygo', '0004_remove_product_size_alter_category_name_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=bidbuygo.models.Product.generate_product_id, max_length=25, primary_key=True, serialize=False),
        ),
    ]
