# Generated by Django 5.2 on 2025-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidbuygo', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('28-30', '28-30'), ('30-32', '30-32'), ('32-34', '32-34'), ('34-36', '34-36'), ('36-38', '36-38'), ('38-40', '38-40'), ('40-42', '40-42'), ('42-44', '42-44'), ('44-46', '44-46'), ('46-48', '46-48'), ('48-50', '48-50'), ('Free', 'Free Size')], max_length=10),
        ),
    ]
