# Generated by Django 5.2 on 2025-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidbuygo', '0015_alter_delivery_order_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
